CREATE TABLE IF NOT EXISTS `students` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `reg_number` varchar(50),
  `pin` varchar(255),
  `dob` date NOT NULL,
  `gender` enum('male', 'female', 'other') NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20),
  `address` text,
  `institution` varchar(150),
  `grade_level` varchar(20) NOT NULL,
  `admission_date` date NOT NULL,
  `status` enum('Pending', 'Admitted', 'Not Admitted') DEFAULT 'Pending',
  `national_id` varchar(50),
  `parent_name` varchar(150),
  `parent_phone` varchar(20),
  `parent_email` varchar(100),
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `reg_number` (`reg_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 